base_settings:
  audio_codec: nvidia/nemo-nano-codec-22khz-0.6kbps-12.5fps
  num_readers: 8
  qsize: 100000
  OUT_DIR: shards 
  gzip_level: 1
  buffer_size: 16777216
  lines_per_file: 50000
  load_dataset_num_proc: 20

save_settings:
  local: /data/3-nano-datasets/Multispeaker          # dataset dir
  hf_upload: null                             # repo/name

hf_datasets:

  - name: /data/2-base-datasets/Anna
    sub_name: null                # Dataset subset/configuration (e.g., 'clean', 'other'), or null
    split: null                   # Dataset split to use ('train', 'test', 'validation', etc.)
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: speaker
    add_constant:     # or null
      - key: speaker
        value: anna
      - key: lang
        value: de

  - name: /data/2-base-datasets/Florian
    sub_name: null                # Dataset subset/configuration (e.g., 'clean', 'other'), or null
    split: null                   # Dataset split to use ('train', 'test', 'validation', etc.)
    text_column_name: text
    audio_column_name: audio
    speaker_column_name: speaker
    add_constant:     # or null
      - key: speaker
        value: florian
      - key: lang
        value: de

